version: '3.8'
services:
  dbs:
    build: ./Workload_Profiler-SQL
    image: vishalkhetmalis/server:postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgress
      - POSTGRES_DB = Services
    networks: 
      - app-network
    ports:
      - '5435:5432'

  python:
    build: ./Workload_Profiler-API
    image: vishalkhetmalis/server:python
    container_name: python
    #command: python bulkload.py
    
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    networks:
      - app-network
    depends_on:
      - dbs
    # restart: always 

networks:
  app-network:
    name: app-network