CREATE TABLE Users( User_Id SERIAL NOT NULL PRIMARY KEY ,Email_Id varchar(50) Not NULL,Password varchar(1000) NOT NULL,First_Name varchar(250) Not NULL,Last_Name varchar(250) NOT NULL,Created_on timestamp without time zone NOT NULL,Created_by varchar not null, Updated_on timestamp without time zone NULL,Updated_by varchar null,Role varchar(20)NOT NULL,Teams Varchar Not NULL,Delete BIT null);
CREATE TABLE Asset(Asset_Id  SERIAL NOT NULL PRIMARY KEY,Asset_Name varchar (50) NOT NULL,Manufacturer varchar NOT NULL, BMC_IP varchar NOT NULL, BMC_User varchar NOT NULL, BMC_Password varchar NOT NULL, Asset_Location varchar NOT NULL,Reserved BOOL, Assigned_to INT,FOREIGN KEY(Assigned_to) REFERENCES Users(User_Id) ,Assigned_from timestamp without time zone null,Assigned_by varchar(50)  null,Created_on timestamp without time zone NOT NULL,Created_by VARCHAR(50)  NULL,Updated_on timestamp without time zone NULL,Updated_by varchar  NULL,OS_IP inet null,OS_User SERIAL  NOT NULL,FOREIGN KEY(OS_User) REFERENCES Users(User_ID) ,OS_Password varchar(1000) null, Purpose varchar(300) NOT NULL,Cluster_Id  Varchar Not NULL, Delete BIT NULL,Status BOOL  NULL );
CREATE TABLE Historic_details(Id SERIAL NOT NULL  PRIMARY KEY,Asset_Id SERIAL NOT NULL ,Assigned_to INT,FOREIGN KEY(Assigned_to) REFERENCES Users(User_Id),FOREIGN KEY(Asset_Id) REFERENCES Asset(Asset_Id),Assigned_from timestamp without time zone NOT NULL,Updated_on timestamp without time zone  NULL,Updated_by varchar not null,Remarks varchar(300)NOT NULL);
CREATE TABLE Platform_Profile(Id SERIAL NOT NULL  PRIMARY KEY,Asset_Id SERIAL NOT NULL,FOREIGN KEY(Asset_Id) REFERENCES Asset(Asset_Id),Ram_gb INT NOT NULL,Storage_gb INT NOT NULL,Cpu_model VARCHAR(100) NOT NULL);
CREATE TABLE Server_Request(Id SERIAL NOT NULL PRIMARY KEY,Creator varchar NOT NULL, Start_Date timestamp without time zone NOT NULL,End_Date timestamp without time zone NOT NULL,Manufacturer varchar(50) NOT NULL,Number_Of_Servers INT NOT NULL,Cpu_model varchar(50)NOT NULL,CPU_Sockets INT NOT NULL,DIMM_Size Varchar(50)NOT NULL,DIMM_Quantity INT NOT NULL,OS_Vendor Varchar(50) NOT NULL,OS_Controller Varchar(50)NOT NULL,OS_Capacity varchar(50)NOT NULL,Disk_Vendor Varchar(50) NOT NULL,Disk_Controller Varchar(50)NOT NULL,Disk_Capacity varchar(50)NOT NULL,Network_Type BOOL NOT NULL,Network_speed varchar(50)NOT NULL,Network_ports INT NOT NULL,Special_Switching_Needs Varchar(100),Infraadmin_Comments TEXT[] null,User_Comments TEXT[] null,Request bool);

INSERT INTO Users(User_Id,Email_Id,Password,First_Name, Last_Name ,Created_on, Created_by,Updated_on,Updated_by,Role,Teams,Delete) VALUES (Default, 'samarthbr@gmail.com','$2a$14$xKApPpBb4qAjcpRqcqCZge.6rn776XIQWYbW6HmXeh45sFOzSubNS','Samarth','BR','12-03-2022','sreedhar','12-03-2022','sreedhar','ADMIN','T1','0');
INSERT INTO Users(User_Id,Email_Id,Password,First_Name, Last_Name ,Created_on, Created_by,Updated_on,Updated_by,Role,Teams,Delete) VALUES (Default, 'divyasuresh@gmail.com','$2a$14$C19/upt5xPh4ys1wgujWQe0kFb7iE6jlYYKkm0nhLkL6qh/FDhoaS ','Divya','Suresh', '11-03-2022','sreedhar','11-03-2022','sreedhar','USER','T2','1'); 
INSERT INTO Users(User_Id,Email_Id,Password,First_Name, Last_Name ,Created_on, Created_by,Updated_on,Updated_by,Role,Teams,Delete) VALUES (Default, 'hemanthKumarhj@gmail.com',' $2a$14$A0oobnVmXKwo8cnuoZLmLe6OXFAhQUxaEEJ/tKrz2/3zzvhJ3tUM.','Hemanthkumar','HJ', '10-03-2022','sreedhar','10-03-2022','sreedhar','USER','T3','1');
INSERT INTO Users(User_Id,Email_Id,Password,First_Name, Last_Name ,Created_on, Created_by,Updated_on,Updated_by,Role,Teams,Delete) VALUES (Default, 'pavanilokesh@gmail.com','$2a$14$/sjefsBdx/qhUfeIsIc2V.qGQCoYG2PJIgmPhm9VXX8gPbZc8RMoW ','Pavani','lokesh', '09-03-2022','sreedhar','09-03-2022','sreedhar','USER','T2','0');
INSERT INTO Users(User_Id,Email_Id,Password,First_Name, Last_Name ,Created_on, Created_by,Updated_on,Updated_by,Role,Teams,Delete) VALUES (Default, 'akshaydk@gmail.com',' $2a$14$1alJSwtkHAnyR9/F3Om3x.hE41L/a.ev8fnYAnz/nADptU9bawYqe','Akshay','DK ','08-03-2022','sreedhar','08-03-2022','sreedhar','INFRA ADMIN','T1','1');

 INSERT INTO Asset(Asset_Id,Asset_name,Manufacturer,BMC_IP,BMC_User,BMC_Password,Asset_Location,Reserved,Assigned_to,Assigned_from,Assigned_by,Created_on,Created_by,Updated_on,Updated_by,OS_IP ,OS_User ,OS_Password ,Purpose,Cluster_ID,Delete,Status) VALUES (Default,'Samarth','IBM','10.0.2.3','user', 'user123','BGL','yes',3,'06-03-22','SREEDHAR','06-03-22','kk','06-03-22','kk','127.6.7.8',1,'Umar@syed766','Linux testing','C1','0',' yes');
INSERT INTO Asset(Asset_Id,Asset_name,Manufacturer,BMC_IP,BMC_User,BMC_Password,Asset_Location,Reserved,Assigned_to,Assigned_from,Assigned_by,Created_on,Created_by,Updated_on,Updated_by,OS_IP ,OS_User ,OS_Password ,Purpose,Cluster_ID,Delete,Status) VALUES (Default,'Divya','cisco','10.0.2.5','admin', 'admin123','MYS','yes',2,'07-03-22','SREEDHAR','07-03-22','kk','07-03-22','kk','127.6.7.8',2,'Umar@syed766','Linux testing','C2','0',' no');
INSERT INTO Asset(Asset_Id,Asset_name,Manufacturer,BMC_IP,BMC_User,BMC_Password,Asset_Location,Reserved,Assigned_to,Assigned_from,Assigned_by,Created_on,Created_by,Updated_on,Updated_by,OS_IP ,OS_User ,OS_Password ,Purpose,Cluster_ID,Delete,Status) VALUES (Default,'Hemanth','IBM','10.0.2.6','user', 'user123','HYD','no',4,'08-03-22','SREEDHAR','08-03-22','kk','08-03-22','kk','127.6.7.8',3,'Umar@syed766','Linux testing','C1','0',' no');
INSERT INTO Asset(Asset_Id,Asset_name,Manufacturer,BMC_IP,BMC_User,BMC_Password,Asset_Location,Reserved,Assigned_to,Assigned_from,Assigned_by,Created_on,Created_by,Updated_on,Updated_by,OS_IP ,OS_User ,OS_Password ,Purpose,Cluster_ID,Delete,Status) VALUES (Default,'Pavani','cisco','10.0.2.7','admin', 'admin123','BGL','yes',4,'09-03-22','SREEDHAR','09-03-22','kk','09-03-22','kk','127.6.7.8',5,'Umar@syed766','Linux testing','C4','0',' yes');
INSERT INTO Asset(Asset_Id,Asset_name,Manufacturer,BMC_IP,BMC_User,BMC_Password,Asset_Location,Reserved,Assigned_to,Assigned_from,Assigned_by,Created_on,Created_by,Updated_on,Updated_by,OS_IP ,OS_User ,OS_Password ,Purpose,Cluster_ID,Delete,Status) VALUES (Default,'Akshay','IBM','10.0.2.7','user', 'user123','HYD','no',2,'10-03-22','SREEDHAR','10-03-22','kk','10-03-22','kk','127.6.7.8',4,'Umar@syed766','Linux testing','C1','0',' no');

    
INSERT INTO Historic_details(ID,Asset_Id,Assigned_to,Assigned_from,Updated_on,Updated_by,Remarks) VALUES (1, 1,3,'06-03-2022','06-07-2022','SREEDHAR', 'Server assigned to manage the cloud EC2 changes');
INSERT INTO Historic_details(ID,Asset_Id,Assigned_to,Assigned_from,Updated_on,Updated_by,Remarks) VALUES (2, 2,2,'07-04-2022','07-08-2022','SREEDHAR', 'Assigned to manage S3 bucket');
INSERT INTO Historic_details(ID,Asset_Id,Assigned_to,Assigned_from,Updated_on,Updated_by,Remarks) VALUES (3, 3,4,'08-05-2022','08-09-2022','SREEDHAR', 'Assigned to manages elastic ip address');
INSERT INTO Historic_details(ID,Asset_Id,Assigned_to,Assigned_from,Updated_on,Updated_by,Remarks) VALUES (4, 4,4,'09-06-2022','09-10-2022','SREEDHAR', 'Assigned to manages the websites backend server');
INSERT INTO Historic_details(ID,Asset_Id,Assigned_to,Assigned_from,Updated_on,Updated_by,Remarks) VALUES (5, 5,2,'10-07-2022','10-11-2022','SREEDHAR', 'Assigned to manages the websites backend server');

INSERT INTO Platform_profile(ID,Asset_Id,Ram_gb,Storage_gb,Cpu_model) VALUES (Default, 1,8,500,'Intel(R)Core(TM)i7-4790CPU@3.60GHz');
INSERT INTO Platform_profile(ID,Asset_Id,Ram_gb,Storage_gb,Cpu_model) VALUES (Default, 2,16,1000,'Intel(R)Core(TM)i7-4790CPU@3.60GHz');
INSERT INTO Platform_profile(ID,Asset_Id,Ram_gb,Storage_gb,Cpu_model) VALUES (Default, 3,32,1000,'Intel(R)Core(TM)i7-4790CPU@3.60GHz');
INSERT INTO Platform_profile(ID,Asset_Id,Ram_gb,Storage_gb,Cpu_model) VALUES (Default, 4,16,200,'Intel(R)Core(TM)i7-4790CPU@3.60GHz');
INSERT INTO Platform_profile(ID,Asset_Id,Ram_gb,Storage_gb,Cpu_model) VALUES (Default, 5,64,500,'Intel(R)Core(TM)i7-4790CPU@3.60GHz');


INSERT INTO Server_Request(ID,Creator,Start_Date,End_Date,Manufacturer,Number_Of_Servers,Cpu_model,CPU_Sockets,DIMM_Size,DIMM_Quantity,OS_Vendor,OS_Controller,OS_Capacity,Disk_Vendor,Disk_Controller,Disk_Capacity,Network_Type,Network_speed,Network_ports,Special_Switching_Needs,Infraadmin_Comments,User_Comments,Request) VALUES (Default,'Sanvi','11-07-2022','12-07-2022','HP',2,'Intel(R)Core(TM)i7-4790CPU@3.60GHz',2,'64gb',4,'Samsung','SAS','1.5TB','sandisk','SATA','1.5TB','yes','1gb',2,'no',Array[NULL],Array[NULL],True);
